### ISSUE TITLE
Reload `nginx` service?

### ISSUE THREAD

**Issue by madsmtm** [Pilskalns/choco-au-packages#1]
Hi, and thanks for creating the awesome `nginx-service` tool. 🎉 

One of the nice features of `nginx` is the ability to reload the configuration without bringing down the entire service.

Do you know if this is possible on windows as well, and if it's possible with `nginx-service`?

**Comment by Pilskalns** [comment]
Hi @madsmtm,

Yes it is possible and I have done it before, but ir requires sending `nginx -s reload` from system user not from _regular_ admin one as the nginx process itself runs as system.

To do this, I used `sysinternals` utility `psexec` where I would start interactive command from as system:
`psexec -s cmd` (from my memories, not sure if this is correct with all arguments). Thenafter you can navigate directories to installation path and then send reload command without issues.

All the systems where I use this package, nginx is not under constant production load, so restarting whole service (which is fast AF) is not an issue to me.

**Comment by madsmtm** [comment]
Thanks for the response, exactly what I was looking for! But yeah, I probably won't use it much either, simply restarting the service is probably good enough :wink:
